/* No Cap — language registry + UI string table.
   English is the source of truth; any key missing from a locale falls back to it.
   Translated keys cover the navigation, hero, section headings, controls,
   verdict vocabulary, settings and Nova's greeting. */

window.NC_LANGS = [
  { code: "en", name: "English", native: "English", dir: "ltr" },
  { code: "es", name: "Spanish", native: "Español", dir: "ltr" },
  { code: "fr", name: "French", native: "Français", dir: "ltr" },
  { code: "de", name: "German", native: "Deutsch", dir: "ltr" },
  { code: "pt", name: "Portuguese", native: "Português", dir: "ltr" },
  { code: "it", name: "Italian", native: "Italiano", dir: "ltr" },
  { code: "nl", name: "Dutch", native: "Nederlands", dir: "ltr" },
  { code: "pl", name: "Polish", native: "Polski", dir: "ltr" },
  { code: "ru", name: "Russian", native: "Русский", dir: "ltr" },
  { code: "uk", name: "Ukrainian", native: "Українська", dir: "ltr" },
  { code: "tr", name: "Turkish", native: "Türkçe", dir: "ltr" },
  { code: "ar", name: "Arabic", native: "العربية", dir: "rtl" },
  { code: "he", name: "Hebrew", native: "עברית", dir: "rtl" },
  { code: "ur", name: "Urdu", native: "اردو", dir: "rtl" },
  { code: "hi", name: "Hindi", native: "हिन्दी", dir: "ltr" },
  { code: "bn", name: "Bengali", native: "বাংলা", dir: "ltr" },
  { code: "ta", name: "Tamil", native: "தமிழ்", dir: "ltr" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia", dir: "ltr" },
  { code: "zh", name: "Chinese (Simplified)", native: "简体中文", dir: "ltr" },
  { code: "ja", name: "Japanese", native: "日本語", dir: "ltr" },
  { code: "ko", name: "Korean", native: "한국어", dir: "ltr" }
];

window.NC_STRINGS = {
  en: {
    nav_home: "Home",
    nav_link: "Link Scanner",
    nav_image: "Image Lab",
    nav_video: "Video Lab",
    nav_news: "News Desk",
    nav_review: "Review Audit",
    nav_message: "Message Guard",
    nav_settings: "Settings",
    hero_title: "Spot the fake before it costs you.",
    hero_lede: "No Cap reads links, images, videos, headlines, reviews and chat messages the way a security analyst would — then explains the verdict in plain language.",
    hero_cta1: "Scan a link",
    hero_cta2: "How it works",
    about_title: "Why No Cap exists",
    about_lede: "Most scams work because nobody has ten spare seconds to check. No Cap gives you those ten seconds back.",
    sec_tools: "Detection suite",
    sec_threats: "Know the attack",
    sec_stats: "Live threat dashboard",
    btn_scan: "Scan",
    btn_analyze: "Analyse",
    btn_upload: "Upload",
    btn_reset: "Reset",
    st_analyzing: "Analysing",
    st_risk: "Risk score",
    st_findings: "Findings",
    st_safe: "Likely safe",
    st_caution: "Caution",
    st_danger: "High risk",
    set_title: "Settings",
    set_theme: "Appearance",
    set_lang: "Language",
    set_motion: "Reduce motion",
    set_cursor: "Custom cursor",
    nova_line: "In a world of fake links, this website is the right guide to a world free of scams!",
    foot_note: "Educational tool. Always confirm with an official source before you pay, click or share."
  },

  es: {
    nav_home: "Inicio", nav_link: "Escáner de enlaces", nav_image: "Laboratorio de imágenes",
    nav_video: "Laboratorio de vídeo", nav_news: "Mesa de noticias", nav_review: "Auditoría de reseñas",
    nav_message: "Guardia de mensajes", nav_settings: "Ajustes",
    hero_title: "Detecta el engaño antes de que te cueste caro.",
    hero_lede: "No Cap analiza enlaces, imágenes, vídeos, titulares, reseñas y mensajes como lo haría un analista de seguridad, y luego explica el veredicto con palabras claras.",
    hero_cta1: "Escanear un enlace", hero_cta2: "Cómo funciona",
    about_title: "Por qué existe No Cap",
    about_lede: "Casi todas las estafas funcionan porque nadie tiene diez segundos para comprobar. No Cap te devuelve esos diez segundos.",
    sec_tools: "Conjunto de detección", sec_threats: "Conoce el ataque", sec_stats: "Panel de amenazas en vivo",
    btn_scan: "Escanear", btn_analyze: "Analizar", btn_upload: "Subir", btn_reset: "Reiniciar",
    st_analyzing: "Analizando", st_risk: "Puntuación de riesgo", st_findings: "Hallazgos",
    st_safe: "Probablemente seguro", st_caution: "Precaución", st_danger: "Riesgo alto",
    set_title: "Ajustes", set_theme: "Apariencia", set_lang: "Idioma", set_motion: "Reducir movimiento", set_cursor: "Cursor personalizado",
    nova_line: "En un mundo de enlaces falsos, ¡esta web es la guía correcta hacia un mundo sin estafas!",
    foot_note: "Herramienta educativa. Confirma siempre con una fuente oficial antes de pagar, hacer clic o compartir."
  },

  fr: {
    nav_home: "Accueil", nav_link: "Scanner de liens", nav_image: "Labo image", nav_video: "Labo vidéo",
    nav_news: "Bureau des news", nav_review: "Audit des avis", nav_message: "Garde-messages", nav_settings: "Paramètres",
    hero_title: "Repérez le faux avant qu'il ne vous coûte cher.",
    hero_lede: "No Cap analyse liens, images, vidéos, titres, avis et messages comme le ferait un analyste en sécurité, puis explique son verdict simplement.",
    hero_cta1: "Analyser un lien", hero_cta2: "Comment ça marche",
    about_title: "Pourquoi No Cap existe",
    about_lede: "La plupart des arnaques réussissent parce que personne n'a dix secondes pour vérifier. No Cap vous rend ces dix secondes.",
    sec_tools: "Suite de détection", sec_threats: "Comprendre l'attaque", sec_stats: "Tableau des menaces en direct",
    btn_scan: "Analyser", btn_analyze: "Analyser", btn_upload: "Téléverser", btn_reset: "Réinitialiser",
    st_analyzing: "Analyse en cours", st_risk: "Score de risque", st_findings: "Constats",
    st_safe: "Probablement sûr", st_caution: "Prudence", st_danger: "Risque élevé",
    set_title: "Paramètres", set_theme: "Apparence", set_lang: "Langue", set_motion: "Réduire les animations", set_cursor: "Curseur personnalisé",
    nova_line: "Dans un monde de faux liens, ce site est le bon guide vers un monde sans arnaques !",
    foot_note: "Outil pédagogique. Vérifiez toujours auprès d'une source officielle avant de payer, cliquer ou partager."
  },

  de: {
    nav_home: "Start", nav_link: "Link-Scanner", nav_image: "Bild-Labor", nav_video: "Video-Labor",
    nav_news: "Nachrichten-Pult", nav_review: "Bewertungs-Audit", nav_message: "Nachrichten-Wache", nav_settings: "Einstellungen",
    hero_title: "Erkenne die Fälschung, bevor sie dich etwas kostet.",
    hero_lede: "No Cap prüft Links, Bilder, Videos, Schlagzeilen, Bewertungen und Chat-Nachrichten wie ein Sicherheitsanalyst – und erklärt das Ergebnis verständlich.",
    hero_cta1: "Link prüfen", hero_cta2: "So funktioniert es",
    about_title: "Warum es No Cap gibt",
    about_lede: "Die meisten Betrugsmaschen funktionieren, weil niemand zehn Sekunden zum Prüfen hat. No Cap gibt dir diese zehn Sekunden zurück.",
    sec_tools: "Erkennungs-Suite", sec_threats: "Den Angriff verstehen", sec_stats: "Live-Bedrohungslage",
    btn_scan: "Prüfen", btn_analyze: "Analysieren", btn_upload: "Hochladen", btn_reset: "Zurücksetzen",
    st_analyzing: "Analyse läuft", st_risk: "Risikowert", st_findings: "Befunde",
    st_safe: "Vermutlich sicher", st_caution: "Vorsicht", st_danger: "Hohes Risiko",
    set_title: "Einstellungen", set_theme: "Darstellung", set_lang: "Sprache", set_motion: "Bewegung reduzieren", set_cursor: "Eigener Mauszeiger",
    nova_line: "In einer Welt voller gefälschter Links ist diese Seite der richtige Wegweiser in eine betrugsfreie Welt!",
    foot_note: "Lernwerkzeug. Prüfe immer bei einer offiziellen Quelle nach, bevor du zahlst, klickst oder teilst."
  },

  pt: {
    nav_home: "Início", nav_link: "Scanner de links", nav_image: "Laboratório de imagem", nav_video: "Laboratório de vídeo",
    nav_news: "Mesa de notícias", nav_review: "Auditoria de avaliações", nav_message: "Guarda de mensagens", nav_settings: "Definições",
    hero_title: "Descubra a falsificação antes que ela custe caro.",
    hero_lede: "O No Cap analisa links, imagens, vídeos, manchetes, avaliações e mensagens como faria um analista de segurança — e explica o veredito em linguagem simples.",
    hero_cta1: "Analisar um link", hero_cta2: "Como funciona",
    about_title: "Porque o No Cap existe",
    about_lede: "Quase todos os golpes funcionam porque ninguém tem dez segundos para verificar. O No Cap devolve esses dez segundos.",
    sec_tools: "Conjunto de deteção", sec_threats: "Conheça o ataque", sec_stats: "Painel de ameaças ao vivo",
    btn_scan: "Analisar", btn_analyze: "Analisar", btn_upload: "Carregar", btn_reset: "Repor",
    st_analyzing: "A analisar", st_risk: "Pontuação de risco", st_findings: "Constatações",
    st_safe: "Provavelmente seguro", st_caution: "Atenção", st_danger: "Risco elevado",
    set_title: "Definições", set_theme: "Aparência", set_lang: "Idioma", set_motion: "Reduzir movimento", set_cursor: "Cursor personalizado",
    nova_line: "Num mundo de links falsos, este site é o guia certo para um mundo livre de golpes!",
    foot_note: "Ferramenta educativa. Confirme sempre numa fonte oficial antes de pagar, clicar ou partilhar."
  },

  it: {
    nav_home: "Home", nav_link: "Scanner link", nav_image: "Laboratorio immagini", nav_video: "Laboratorio video",
    nav_news: "Redazione notizie", nav_review: "Audit recensioni", nav_message: "Guardia messaggi", nav_settings: "Impostazioni",
    hero_title: "Riconosci il falso prima che ti costi caro.",
    hero_lede: "No Cap esamina link, immagini, video, titoli, recensioni e messaggi come farebbe un analista di sicurezza, poi spiega il verdetto in parole semplici.",
    hero_cta1: "Analizza un link", hero_cta2: "Come funziona",
    about_title: "Perché esiste No Cap",
    about_lede: "Quasi tutte le truffe riescono perché nessuno ha dieci secondi per controllare. No Cap ti restituisce quei dieci secondi.",
    sec_tools: "Suite di rilevamento", sec_threats: "Conosci l'attacco", sec_stats: "Cruscotto minacce in tempo reale",
    btn_scan: "Analizza", btn_analyze: "Analizza", btn_upload: "Carica", btn_reset: "Reimposta",
    st_analyzing: "Analisi in corso", st_risk: "Punteggio di rischio", st_findings: "Riscontri",
    st_safe: "Probabilmente sicuro", st_caution: "Attenzione", st_danger: "Rischio elevato",
    set_title: "Impostazioni", set_theme: "Aspetto", set_lang: "Lingua", set_motion: "Riduci le animazioni", set_cursor: "Cursore personalizzato",
    nova_line: "In un mondo di link falsi, questo sito è la guida giusta verso un mondo senza truffe!",
    foot_note: "Strumento didattico. Verifica sempre con una fonte ufficiale prima di pagare, cliccare o condividere."
  },

  nl: {
    nav_home: "Start", nav_link: "Linkscanner", nav_image: "Beeldlab", nav_video: "Videolab",
    nav_news: "Nieuwsdesk", nav_review: "Recensie-audit", nav_message: "Berichtwacht", nav_settings: "Instellingen",
    hero_title: "Herken de vervalsing voordat die je geld kost.",
    hero_lede: "No Cap leest links, afbeeldingen, video's, koppen, recensies en chatberichten zoals een securityanalist dat doet — en legt het oordeel in gewone taal uit.",
    hero_cta1: "Link scannen", hero_cta2: "Zo werkt het",
    about_title: "Waarom No Cap bestaat",
    about_lede: "De meeste oplichting slaagt omdat niemand tien seconden heeft om iets te controleren. No Cap geeft je die tien seconden terug.",
    sec_tools: "Detectiesuite", sec_threats: "Ken de aanval", sec_stats: "Live dreigingsdashboard",
    btn_scan: "Scannen", btn_analyze: "Analyseren", btn_upload: "Uploaden", btn_reset: "Wissen",
    st_analyzing: "Bezig met analyseren", st_risk: "Risicoscore", st_findings: "Bevindingen",
    st_safe: "Waarschijnlijk veilig", st_caution: "Let op", st_danger: "Hoog risico",
    set_title: "Instellingen", set_theme: "Weergave", set_lang: "Taal", set_motion: "Minder beweging", set_cursor: "Aangepaste cursor",
    nova_line: "In een wereld vol neplinks is deze website de juiste gids naar een wereld zonder oplichting!",
    foot_note: "Educatief hulpmiddel. Controleer altijd bij een officiële bron voordat je betaalt, klikt of deelt."
  },

  pl: {
    nav_home: "Start", nav_link: "Skaner linków", nav_image: "Laboratorium zdjęć", nav_video: "Laboratorium wideo",
    nav_news: "Dział wiadomości", nav_review: "Audyt opinii", nav_message: "Strażnik wiadomości", nav_settings: "Ustawienia",
    hero_title: "Rozpoznaj fałszywkę, zanim cię zaboli.",
    hero_lede: "No Cap czyta linki, zdjęcia, filmy, nagłówki, opinie i wiadomości tak jak analityk bezpieczeństwa — a potem tłumaczy werdykt prostym językiem.",
    hero_cta1: "Sprawdź link", hero_cta2: "Jak to działa",
    about_title: "Po co powstał No Cap",
    about_lede: "Większość oszustw działa, bo nikt nie ma dziesięciu sekund na sprawdzenie. No Cap oddaje ci te dziesięć sekund.",
    sec_tools: "Zestaw wykrywania", sec_threats: "Poznaj atak", sec_stats: "Panel zagrożeń na żywo",
    btn_scan: "Skanuj", btn_analyze: "Analizuj", btn_upload: "Prześlij", btn_reset: "Wyczyść",
    st_analyzing: "Analizowanie", st_risk: "Ocena ryzyka", st_findings: "Ustalenia",
    st_safe: "Prawdopodobnie bezpieczne", st_caution: "Ostrożnie", st_danger: "Wysokie ryzyko",
    set_title: "Ustawienia", set_theme: "Wygląd", set_lang: "Język", set_motion: "Ogranicz animacje", set_cursor: "Własny kursor",
    nova_line: "W świecie fałszywych linków ta strona jest właściwym przewodnikiem do świata bez oszustw!",
    foot_note: "Narzędzie edukacyjne. Zawsze potwierdź w oficjalnym źródle, zanim zapłacisz, klikniesz lub udostępnisz."
  },

  ru: {
    nav_home: "Главная", nav_link: "Сканер ссылок", nav_image: "Лаборатория изображений", nav_video: "Лаборатория видео",
    nav_news: "Новостной отдел", nav_review: "Аудит отзывов", nav_message: "Защита сообщений", nav_settings: "Настройки",
    hero_title: "Распознайте подделку, пока она не стоила вам денег.",
    hero_lede: "No Cap разбирает ссылки, изображения, видео, заголовки, отзывы и сообщения так, как это сделал бы аналитик по безопасности, и объясняет вывод простыми словами.",
    hero_cta1: "Проверить ссылку", hero_cta2: "Как это работает",
    about_title: "Зачем нужен No Cap",
    about_lede: "Большинство мошенничеств срабатывает потому, что ни у кого нет десяти секунд на проверку. No Cap возвращает вам эти десять секунд.",
    sec_tools: "Набор детекторов", sec_threats: "Изучите атаку", sec_stats: "Панель угроз в реальном времени",
    btn_scan: "Сканировать", btn_analyze: "Анализировать", btn_upload: "Загрузить", btn_reset: "Сбросить",
    st_analyzing: "Анализ", st_risk: "Оценка риска", st_findings: "Результаты проверки",
    st_safe: "Скорее всего безопасно", st_caution: "Осторожно", st_danger: "Высокий риск",
    set_title: "Настройки", set_theme: "Оформление", set_lang: "Язык", set_motion: "Меньше анимации", set_cursor: "Свой курсор",
    nova_line: "В мире фальшивых ссылок этот сайт — верный проводник в мир без мошенничества!",
    foot_note: "Образовательный инструмент. Всегда проверяйте официальный источник, прежде чем платить, переходить или делиться."
  },

  uk: {
    nav_home: "Головна", nav_link: "Сканер посилань", nav_image: "Лабораторія зображень", nav_video: "Лабораторія відео",
    nav_news: "Відділ новин", nav_review: "Аудит відгуків", nav_message: "Захист повідомлень", nav_settings: "Налаштування",
    hero_title: "Розпізнайте підробку, доки вона не коштувала вам грошей.",
    hero_lede: "No Cap читає посилання, зображення, відео, заголовки, відгуки та повідомлення так, як це робить аналітик безпеки, і пояснює висновок простою мовою.",
    hero_cta1: "Перевірити посилання", hero_cta2: "Як це працює",
    about_title: "Навіщо існує No Cap",
    about_lede: "Більшість шахрайств спрацьовує тому, що ні в кого немає десяти секунд на перевірку. No Cap повертає вам ці десять секунд.",
    sec_tools: "Набір детекторів", sec_threats: "Вивчіть атаку", sec_stats: "Панель загроз наживо",
    btn_scan: "Сканувати", btn_analyze: "Аналізувати", btn_upload: "Завантажити", btn_reset: "Скинути",
    st_analyzing: "Аналізуємо", st_risk: "Оцінка ризику", st_findings: "Висновки",
    st_safe: "Ймовірно безпечно", st_caution: "Обережно", st_danger: "Високий ризик",
    set_title: "Налаштування", set_theme: "Вигляд", set_lang: "Мова", set_motion: "Менше анімації", set_cursor: "Власний курсор",
    nova_line: "У світі фальшивих посилань цей сайт — правильний провідник у світ без шахрайства!",
    foot_note: "Освітній інструмент. Завжди перевіряйте офіційне джерело, перш ніж платити, натискати чи ділитися."
  },

  tr: {
    nav_home: "Ana sayfa", nav_link: "Bağlantı tarayıcı", nav_image: "Görsel laboratuvarı", nav_video: "Video laboratuvarı",
    nav_news: "Haber masası", nav_review: "Yorum denetimi", nav_message: "Mesaj koruması", nav_settings: "Ayarlar",
    hero_title: "Sahteyi size pahalıya patlamadan yakalayın.",
    hero_lede: "No Cap; bağlantıları, görselleri, videoları, başlıkları, yorumları ve mesajları bir güvenlik analistinin gözüyle inceler ve sonucu sade bir dille anlatır.",
    hero_cta1: "Bağlantı tara", hero_cta2: "Nasıl çalışır",
    about_title: "No Cap neden var",
    about_lede: "Dolandırıcılıkların çoğu, kimsenin kontrol edecek on saniyesi olmadığı için işe yarar. No Cap o on saniyeyi size geri verir.",
    sec_tools: "Tespit takımı", sec_threats: "Saldırıyı tanı", sec_stats: "Canlı tehdit panosu",
    btn_scan: "Tara", btn_analyze: "Analiz et", btn_upload: "Yükle", btn_reset: "Sıfırla",
    st_analyzing: "Analiz ediliyor", st_risk: "Risk puanı", st_findings: "Bulgular",
    st_safe: "Muhtemelen güvenli", st_caution: "Dikkat", st_danger: "Yüksek risk",
    set_title: "Ayarlar", set_theme: "Görünüm", set_lang: "Dil", set_motion: "Hareketi azalt", set_cursor: "Özel imleç",
    nova_line: "Sahte bağlantılarla dolu bir dünyada, bu site dolandırıcılıksız bir dünyaya giden doğru rehber!",
    foot_note: "Eğitim amaçlı bir araçtır. Ödeme yapmadan, tıklamadan veya paylaşmadan önce resmi kaynaktan doğrulayın."
  },

  ar: {
    nav_home: "الرئيسية", nav_link: "فاحص الروابط", nav_image: "مختبر الصور", nav_video: "مختبر الفيديو",
    nav_news: "مكتب الأخبار", nav_review: "تدقيق المراجعات", nav_message: "حارس الرسائل", nav_settings: "الإعدادات",
    hero_title: "اكشف المزيّف قبل أن يكلّفك.",
    hero_lede: "يفحص No Cap الروابط والصور والفيديوهات والعناوين والمراجعات والرسائل كما يفعل محلل الأمن، ثم يشرح النتيجة بلغة بسيطة.",
    hero_cta1: "افحص رابطًا", hero_cta2: "كيف يعمل",
    about_title: "لماذا وُجد No Cap",
    about_lede: "معظم عمليات الاحتيال تنجح لأن لا أحد يملك عشر ثوانٍ للتحقق. No Cap يعيد لك هذه الثواني العشر.",
    sec_tools: "حزمة الكشف", sec_threats: "اعرف الهجوم", sec_stats: "لوحة التهديدات المباشرة",
    btn_scan: "فحص", btn_analyze: "تحليل", btn_upload: "رفع", btn_reset: "إعادة ضبط",
    st_analyzing: "جارٍ التحليل", st_risk: "درجة الخطورة", st_findings: "النتائج",
    st_safe: "آمن على الأرجح", st_caution: "احذر", st_danger: "خطورة عالية",
    set_title: "الإعدادات", set_theme: "المظهر", set_lang: "اللغة", set_motion: "تقليل الحركة", set_cursor: "مؤشر مخصص",
    nova_line: "في عالم مليء بالروابط المزيفة، هذا الموقع هو الدليل الصحيح إلى عالم خالٍ من الاحتيال!",
    foot_note: "أداة تعليمية. تحقّق دائمًا من مصدر رسمي قبل الدفع أو النقر أو المشاركة."
  },

  he: {
    nav_home: "בית", nav_link: "סורק קישורים", nav_image: "מעבדת תמונות", nav_video: "מעבדת וידאו",
    nav_news: "דסק חדשות", nav_review: "ביקורת ביקורות", nav_message: "שומר הודעות", nav_settings: "הגדרות",
    hero_title: "זהו את הזיוף לפני שהוא יעלה לכם ביוקר.",
    hero_lede: "No Cap בוחן קישורים, תמונות, סרטונים, כותרות, ביקורות והודעות כמו אנליסט אבטחה, ואז מסביר את המסקנה בשפה פשוטה.",
    hero_cta1: "סרוק קישור", hero_cta2: "איך זה עובד",
    about_title: "למה No Cap קיים",
    about_lede: "רוב ההונאות מצליחות כי לאף אחד אין עשר שניות לבדוק. No Cap מחזיר לכם את עשר השניות האלה.",
    sec_tools: "ערכת הזיהוי", sec_threats: "הכירו את המתקפה", sec_stats: "לוח איומים חי",
    btn_scan: "סריקה", btn_analyze: "ניתוח", btn_upload: "העלאה", btn_reset: "איפוס",
    st_analyzing: "מנתח", st_risk: "ציון סיכון", st_findings: "ממצאים",
    st_safe: "כנראה בטוח", st_caution: "זהירות", st_danger: "סיכון גבוה",
    set_title: "הגדרות", set_theme: "מראה", set_lang: "שפה", set_motion: "הפחתת תנועה", set_cursor: "סמן מותאם",
    nova_line: "בעולם של קישורים מזויפים, האתר הזה הוא המדריך הנכון לעולם ללא הונאות!",
    foot_note: "כלי לימודי. תמיד אמתו מול מקור רשמי לפני שאתם משלמים, לוחצים או משתפים."
  },

  ur: {
    nav_home: "ہوم", nav_link: "لنک اسکینر", nav_image: "تصویری لیب", nav_video: "ویڈیو لیب",
    nav_news: "نیوز ڈیسک", nav_review: "ریویو آڈٹ", nav_message: "پیغام محافظ", nav_settings: "ترتیبات",
    hero_title: "نقصان سے پہلے جعل سازی پہچانیں۔",
    hero_lede: "No Cap لنکس، تصاویر، ویڈیوز، سرخیوں، ریویوز اور پیغامات کو ایک سیکیورٹی تجزیہ کار کی طرح جانچتا ہے اور نتیجہ آسان زبان میں بتاتا ہے۔",
    hero_cta1: "لنک اسکین کریں", hero_cta2: "یہ کیسے کام کرتا ہے",
    about_title: "No Cap کیوں بنا",
    about_lede: "زیادہ تر فراڈ اس لیے کامیاب ہوتے ہیں کہ کسی کے پاس جانچنے کے دس سیکنڈ نہیں ہوتے۔ No Cap آپ کو وہ دس سیکنڈ واپس دیتا ہے۔",
    sec_tools: "شناختی مجموعہ", sec_threats: "حملے کو سمجھیں", sec_stats: "لائیو خطرات ڈیش بورڈ",
    btn_scan: "اسکین", btn_analyze: "تجزیہ", btn_upload: "اپ لوڈ", btn_reset: "ری سیٹ",
    st_analyzing: "تجزیہ جاری ہے", st_risk: "خطرے کا اسکور", st_findings: "نتائج",
    st_safe: "غالباً محفوظ", st_caution: "احتیاط", st_danger: "زیادہ خطرہ",
    set_title: "ترتیبات", set_theme: "ظاہری شکل", set_lang: "زبان", set_motion: "حرکت کم کریں", set_cursor: "اپنی مرضی کا کرسر",
    nova_line: "جعلی لنکس کی دنیا میں، یہ ویب سائٹ فراڈ سے پاک دنیا کی درست رہنما ہے!",
    foot_note: "تعلیمی ذریعہ۔ ادائیگی، کلک یا شیئر کرنے سے پہلے ہمیشہ سرکاری ذریعے سے تصدیق کریں۔"
  },

  hi: {
    nav_home: "होम", nav_link: "लिंक स्कैनर", nav_image: "इमेज लैब", nav_video: "वीडियो लैब",
    nav_news: "न्यूज़ डेस्क", nav_review: "रिव्यू ऑडिट", nav_message: "मैसेज गार्ड", nav_settings: "सेटिंग्स",
    hero_title: "नुकसान होने से पहले नकली को पहचानें।",
    hero_lede: "No Cap लिंक, तस्वीरें, वीडियो, सुर्खियाँ, रिव्यू और चैट मैसेज को एक सुरक्षा विश्लेषक की तरह जाँचता है और नतीजा आसान भाषा में समझाता है।",
    hero_cta1: "लिंक स्कैन करें", hero_cta2: "यह कैसे काम करता है",
    about_title: "No Cap क्यों बना",
    about_lede: "ज़्यादातर घोटाले इसलिए सफल होते हैं क्योंकि किसी के पास जाँचने के दस सेकंड नहीं होते। No Cap वे दस सेकंड आपको लौटा देता है।",
    sec_tools: "डिटेक्शन सूट", sec_threats: "हमले को समझें", sec_stats: "लाइव थ्रेट डैशबोर्ड",
    btn_scan: "स्कैन", btn_analyze: "विश्लेषण", btn_upload: "अपलोड", btn_reset: "रीसेट",
    st_analyzing: "विश्लेषण जारी", st_risk: "जोखिम स्कोर", st_findings: "निष्कर्ष",
    st_safe: "संभवतः सुरक्षित", st_caution: "सावधानी", st_danger: "उच्च जोखिम",
    set_title: "सेटिंग्स", set_theme: "रूप", set_lang: "भाषा", set_motion: "एनिमेशन कम करें", set_cursor: "कस्टम कर्सर",
    nova_line: "नकली लिंक की दुनिया में, यह वेबसाइट घोटालों से मुक्त दुनिया की सही राह दिखाती है!",
    foot_note: "शैक्षिक साधन। भुगतान, क्लिक या साझा करने से पहले हमेशा आधिकारिक स्रोत से पुष्टि करें।"
  },

  bn: {
    nav_home: "হোম", nav_link: "লিংক স্ক্যানার", nav_image: "ইমেজ ল্যাব", nav_video: "ভিডিও ল্যাব",
    nav_news: "নিউজ ডেস্ক", nav_review: "রিভিউ অডিট", nav_message: "মেসেজ গার্ড", nav_settings: "সেটিংস",
    hero_title: "ক্ষতি হওয়ার আগেই নকল চিনে নিন।",
    hero_lede: "No Cap লিংক, ছবি, ভিডিও, শিরোনাম, রিভিউ ও বার্তা একজন নিরাপত্তা বিশ্লেষকের মতো পরীক্ষা করে এবং ফলাফল সহজ ভাষায় বুঝিয়ে দেয়।",
    hero_cta1: "লিংক স্ক্যান করুন", hero_cta2: "কীভাবে কাজ করে",
    about_title: "No Cap কেন",
    about_lede: "বেশিরভাগ প্রতারণা সফল হয় কারণ যাচাই করার দশ সেকেন্ড কারও থাকে না। No Cap সেই দশ সেকেন্ড ফিরিয়ে দেয়।",
    sec_tools: "শনাক্তকরণ স্যুট", sec_threats: "আক্রমণ চিনুন", sec_stats: "লাইভ হুমকি ড্যাশবোর্ড",
    btn_scan: "স্ক্যান", btn_analyze: "বিশ্লেষণ", btn_upload: "আপলোড", btn_reset: "রিসেট",
    st_analyzing: "বিশ্লেষণ চলছে", st_risk: "ঝুঁকির স্কোর", st_findings: "ফলাফল",
    st_safe: "সম্ভবত নিরাপদ", st_caution: "সতর্কতা", st_danger: "উচ্চ ঝুঁকি",
    set_title: "সেটিংস", set_theme: "চেহারা", set_lang: "ভাষা", set_motion: "অ্যানিমেশন কমান", set_cursor: "কাস্টম কার্সর",
    nova_line: "নকল লিংকের দুনিয়ায় এই ওয়েবসাইটই প্রতারণামুক্ত দুনিয়ার সঠিক পথপ্রদর্শক!",
    foot_note: "শিক্ষামূলক টুল। অর্থ দেওয়ার, ক্লিক করার বা শেয়ার করার আগে সবসময় সরকারি বা অফিসিয়াল উৎসে যাচাই করুন।"
  },

  ta: {
    nav_home: "முகப்பு", nav_link: "இணைப்பு ஸ்கேனர்", nav_image: "பட ஆய்வகம்", nav_video: "வீடியோ ஆய்வகம்",
    nav_news: "செய்திப் பிரிவு", nav_review: "விமர்சன தணிக்கை", nav_message: "செய்தி காவலர்", nav_settings: "அமைப்புகள்",
    hero_title: "இழப்பு வருவதற்கு முன் போலியை கண்டறியுங்கள்.",
    hero_lede: "No Cap இணைப்புகள், படங்கள், வீடியோக்கள், தலைப்புச் செய்திகள், விமர்சனங்கள், செய்திகளை பாதுகாப்பு ஆய்வாளர் போல் ஆராய்ந்து முடிவை எளிய மொழியில் விளக்குகிறது.",
    hero_cta1: "இணைப்பை ஸ்கேன் செய்", hero_cta2: "எப்படி வேலை செய்கிறது",
    about_title: "No Cap ஏன்",
    about_lede: "பெரும்பாலான மோசடிகள் வெற்றி பெறுவது, சரிபார்க்க பத்து வினாடிகள் யாரிடமும் இல்லாததால்தான். No Cap அந்த பத்து வினாடிகளைத் திரும்பத் தருகிறது.",
    sec_tools: "கண்டறிதல் தொகுப்பு", sec_threats: "தாக்குதலை அறிக", sec_stats: "நேரடி அச்சுறுத்தல் டாஷ்போர்டு",
    btn_scan: "ஸ்கேன்", btn_analyze: "பகுப்பாய்வு", btn_upload: "பதிவேற்று", btn_reset: "மீட்டமை",
    st_analyzing: "பகுப்பாய்வு நடக்கிறது", st_risk: "ஆபத்து மதிப்பெண்", st_findings: "கண்டறிதல்கள்",
    st_safe: "பெரும்பாலும் பாதுகாப்பானது", st_caution: "எச்சரிக்கை", st_danger: "அதிக ஆபத்து",
    set_title: "அமைப்புகள்", set_theme: "தோற்றம்", set_lang: "மொழி", set_motion: "அசைவைக் குறை", set_cursor: "தனிப்பயன் கர்சர்",
    nova_line: "போலி இணைப்புகள் நிறைந்த உலகில், மோசடி இல்லாத உலகிற்கு இந்த இணையதளமே சரியான வழிகாட்டி!",
    foot_note: "கல்விக் கருவி. பணம் செலுத்தும், கிளிக் செய்யும் அல்லது பகிரும் முன் அதிகாரப்பூர்வ ஆதாரத்தில் உறுதி செய்யுங்கள்."
  },

  id: {
    nav_home: "Beranda", nav_link: "Pemindai tautan", nav_image: "Lab gambar", nav_video: "Lab video",
    nav_news: "Meja berita", nav_review: "Audit ulasan", nav_message: "Penjaga pesan", nav_settings: "Pengaturan",
    hero_title: "Kenali yang palsu sebelum merugikan Anda.",
    hero_lede: "No Cap membaca tautan, gambar, video, judul berita, ulasan, dan pesan seperti analis keamanan — lalu menjelaskan hasilnya dengan bahasa sederhana.",
    hero_cta1: "Pindai tautan", hero_cta2: "Cara kerjanya",
    about_title: "Mengapa No Cap ada",
    about_lede: "Sebagian besar penipuan berhasil karena tak ada yang punya sepuluh detik untuk memeriksa. No Cap mengembalikan sepuluh detik itu.",
    sec_tools: "Rangkaian deteksi", sec_threats: "Kenali serangannya", sec_stats: "Dasbor ancaman langsung",
    btn_scan: "Pindai", btn_analyze: "Analisis", btn_upload: "Unggah", btn_reset: "Atur ulang",
    st_analyzing: "Menganalisis", st_risk: "Skor risiko", st_findings: "Temuan",
    st_safe: "Kemungkinan aman", st_caution: "Hati-hati", st_danger: "Risiko tinggi",
    set_title: "Pengaturan", set_theme: "Tampilan", set_lang: "Bahasa", set_motion: "Kurangi gerakan", set_cursor: "Kursor khusus",
    nova_line: "Di dunia penuh tautan palsu, situs ini adalah pemandu yang tepat menuju dunia bebas penipuan!",
    foot_note: "Alat edukasi. Selalu konfirmasi ke sumber resmi sebelum membayar, mengeklik, atau membagikan."
  },

  zh: {
    nav_home: "首页", nav_link: "链接扫描", nav_image: "图像实验室", nav_video: "视频实验室",
    nav_news: "新闻台", nav_review: "评论审计", nav_message: "消息卫士", nav_settings: "设置",
    hero_title: "在受骗之前识破假象。",
    hero_lede: "No Cap 像安全分析师一样审视链接、图片、视频、标题、评论和聊天消息，并用通俗的语言解释判断结果。",
    hero_cta1: "扫描链接", hero_cta2: "工作原理",
    about_title: "No Cap 为何存在",
    about_lede: "大多数骗局之所以得逞，是因为没人愿意花十秒钟去核实。No Cap 把这十秒钟还给你。",
    sec_tools: "检测套件", sec_threats: "认识攻击手法", sec_stats: "实时威胁面板",
    btn_scan: "扫描", btn_analyze: "分析", btn_upload: "上传", btn_reset: "重置",
    st_analyzing: "分析中", st_risk: "风险评分", st_findings: "检测结果",
    st_safe: "大概率安全", st_caution: "需谨慎", st_danger: "高风险",
    set_title: "设置", set_theme: "外观", set_lang: "语言", set_motion: "减少动效", set_cursor: "自定义光标",
    nova_line: "在充满虚假链接的世界里，这个网站就是通往无诈骗世界的正确指引！",
    foot_note: "教育用途工具。付款、点击或转发之前，请务必向官方渠道核实。"
  },

  ja: {
    nav_home: "ホーム", nav_link: "リンク検査", nav_image: "画像ラボ", nav_video: "動画ラボ",
    nav_news: "ニュースデスク", nav_review: "レビュー監査", nav_message: "メッセージ防衛", nav_settings: "設定",
    hero_title: "被害に遭う前に、偽物を見抜く。",
    hero_lede: "No Cap はリンク・画像・動画・見出し・レビュー・メッセージをセキュリティアナリストの視点で調べ、その判定をわかりやすく説明します。",
    hero_cta1: "リンクを検査", hero_cta2: "仕組みを見る",
    about_title: "No Cap が存在する理由",
    about_lede: "詐欺の多くは、確認する十秒を誰も持っていないから成立します。No Cap はその十秒を取り戻します。",
    sec_tools: "検出スイート", sec_threats: "攻撃を知る", sec_stats: "リアルタイム脅威ダッシュボード",
    btn_scan: "検査", btn_analyze: "解析", btn_upload: "アップロード", btn_reset: "リセット",
    st_analyzing: "解析中", st_risk: "リスクスコア", st_findings: "検出結果",
    st_safe: "おそらく安全", st_caution: "注意", st_danger: "高リスク",
    set_title: "設定", set_theme: "外観", set_lang: "言語", set_motion: "動きを減らす", set_cursor: "カスタムカーソル",
    nova_line: "偽リンクだらけの世界で、このサイトは詐欺のない世界への正しい道しるべです！",
    foot_note: "学習用ツールです。支払い・クリック・共有の前に必ず公式の情報源で確認してください。"
  },

  ko: {
    nav_home: "홈", nav_link: "링크 스캐너", nav_image: "이미지 랩", nav_video: "영상 랩",
    nav_news: "뉴스 데스크", nav_review: "리뷰 감사", nav_message: "메시지 가드", nav_settings: "설정",
    hero_title: "피해를 입기 전에 가짜를 알아채세요.",
    hero_lede: "No Cap은 링크, 이미지, 영상, 헤드라인, 리뷰, 메시지를 보안 분석가처럼 살펴보고 그 판단을 쉬운 말로 설명합니다.",
    hero_cta1: "링크 검사", hero_cta2: "작동 방식",
    about_title: "No Cap이 존재하는 이유",
    about_lede: "대부분의 사기는 확인할 십 초가 없어서 성공합니다. No Cap은 그 십 초를 돌려줍니다.",
    sec_tools: "탐지 도구 모음", sec_threats: "공격 이해하기", sec_stats: "실시간 위협 대시보드",
    btn_scan: "검사", btn_analyze: "분석", btn_upload: "업로드", btn_reset: "초기화",
    st_analyzing: "분석 중", st_risk: "위험 점수", st_findings: "발견 사항",
    st_safe: "안전할 가능성 높음", st_caution: "주의", st_danger: "높은 위험",
    set_title: "설정", set_theme: "화면 모드", set_lang: "언어", set_motion: "모션 줄이기", set_cursor: "맞춤 커서",
    nova_line: "가짜 링크로 가득한 세상에서, 이 사이트가 사기 없는 세상으로 가는 올바른 안내자입니다!",
    foot_note: "교육용 도구입니다. 결제하거나 클릭하거나 공유하기 전에 항상 공식 출처로 확인하세요."
  }
};
